//     ----------     ----------     ----------     ----------     ----------
//
//                              AsLib - Asライブラリ
//
//                    制作者: がっちょ (wanotaitei@gmail.com)
//
//     ----------     ----------     ----------     ----------     ----------


namespace AsLib
{
	//キーボード配列ID
	enum :size_t {
		Keyboard_Unknown,
		Keyboard_Grave_Accent_and_Tilde,
		Keyboard_1_and_exclamation,
		Keyboard_2_and_at,
		Keyboard_3_and_number,
		Keyboard_4_and_$,
		Keyboard_5_and_percent,
		Keyboard_6_and_circumflex,
		Keyboard_7_and_ampersand,
		Keyboard_8_and_asterisk,
		Keyboard_9_and_left_parenthesis,
		Keyboard_0_and_right_parenthesis,
		Keyboard_hyphen_and_underscore,
		Keyboard_equal_and_plus,
		Keyboard_International3,
		Keyboard_DELETE_Backspace,
		Keyboard_Tab,
		Keyboard_q_and_Q,
		Keyboard_w_and_W,
		Keyboard_e_and_E,
		Keyboard_r_and_R,
		Keyboard_t_and_T,
		Keyboard_y_and_Y,
		Keyboard_u_and_U,
		Keyboard_i_and_I,
		Keyboard_o_and_O,
		Keyboard_p_and_P,
		Keyboard_left_square_bracket_and_left_curly_bracket,
		Keyboard_right_square_bracket_and_right_curly_bracket,
		Keyboard_＼_and_vertical_line,
		Keyboard_Caps_Lock,
		Keyboard_a_and_A,
		Keyboard_s_and_S,
		Keyboard_d_and_D,
		Keyboard_f_and_F,
		Keyboard_g_and_G,
		Keyboard_h_and_H,
		Keyboard_j_and_J,
		Keyboard_k_and_K,
		Keyboard_l_and_L,
		Keyboard_semicolon_and_colon,
		Keyboard_‘_and_“,
		Keyboard_Non_US_number_and_tilde,
		Keyboard_Return_ENTER,
		Keyboard_LeftShift,
		Keyboard_Unknown1,
		Keyboard_z_and_Z,
		Keyboard_x_and_X,
		Keyboard_c_and_C,
		Keyboard_v_and_V,
		Keyboard_b_and_B,
		Keyboard_n_and_N,
		Keyboard_m_and_M,
		Keyboard_comma_and_less_than_sign,
		Keyboard_full_stop_and_greater_than_sign,
		Keyboard_solidus_and_question,
		Keyboard_International1,
		Keyboard_RightShift,
		Keyboard_LeftControl,
		Keyboard_Unknown2,
		Keyboard_LeftAlt,
		Keyboard_Spacebar,
		Keyboard_RightAlt,
		Keyboard_Unknown3,
		Keyboard_RightControl,
		Keyboard_Unknown4,
		Keyboard_Unknown5,
		Keyboard_Unknown6,
		Keyboard_Unknown7,
		Keyboard_Unknown8,
		Keyboard_Unknown9,
		Keyboard_Unknown10,
		Keyboard_Unknown11,
		Keyboard_Unknown12,
		Keyboard_Unknown13,
		Keyboard_Insert,
		Keyboard_Delete_Forward,
		Keyboard_Unknown14,
		Keyboard_Unknown15,
		Keyboard_LeftArrow,
		Keyboard_Home,
		Keyboard_End,
		Keyboard_Unknown16,
		Keyboard_UpArrow,
		Keyboard_DownArrow,
		Keyboard_PageUp,
		Keyboard_PageDown,
		Keyboard_Unknown17,
		Keyboard_Unknown18,
		Keyboard_RightArrow,
		Keypad_Num_Lock_and_Clear,
		Keypad_7_and_Home,
		Keypad_4_and_Left_Arrow,
		Keypad_1_and_End,
		Keyboard_Unknown19,
		Keypad_solidus,
		Keypad_8_and_Up_Arrow,
		Keypad_5,
		Keypad_2_and_Down_Arrow,
		Keypad_0_and_Insert,
		Keypad_asterisk,
		Keypad_9_and_PageUp,
		Keypad_6_and_Right_Arrow,
		Keypad_3_and_PageDn,
		Keypad_full_stop_and_Delete,
		Keypad_hyphen,
		Keypad_plus,
		Keyboard_Unknown20,
		Keypad_ENTER,
		Keyboard_Unknown21,
		Keyboard_ESCAPE,
		Keyboard_Unknown22,
		Keyboard_F1,
		Keyboard_F2,
		Keyboard_F3,
		Keyboard_F4,
		Keyboard_F5,
		Keyboard_F6,
		Keyboard_F7,
		Keyboard_F8,
		Keyboard_F9,
		Keyboard_F10,
		Keyboard_F11,
		Keyboard_F12,
		Keyboard_PrintScreen,
		Keyboard_Scroll_Lock,
		Keyboard_Pause,
		Keyboard_Left_GUI,
		Keyboard_Right_GUI,
		Keyboard_Application,
		Keyboard_Unknown23,
		Keyboard_International5,
		Keyboard_International4,
		Keyboard_International2,
	};

#if defined(ASLIB_INCLUDE_DL) //DxLib

#elif defined(ASLIB_INCLUDE_S3) //Siv3D

#else //Console

#endif

}
